/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettlementsRouteImport } from './routes/settlements'
import { Route as ImportReportsRouteImport } from './routes/import-reports'
import { Route as ImportCsvRouteImport } from './routes/import-csv'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as BalancesRouteImport } from './routes/balances'
import { Route as IndexRouteImport } from './routes/index'

const SettlementsRoute = SettlementsRouteImport.update({
  id: '/settlements',
  path: '/settlements',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportReportsRoute = ImportReportsRouteImport.update({
  id: '/import-reports',
  path: '/import-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportCsvRoute = ImportCsvRouteImport.update({
  id: '/import-csv',
  path: '/import-csv',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const BalancesRoute = BalancesRouteImport.update({
  id: '/balances',
  path: '/balances',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/balances': typeof BalancesRoute
  '/expenses': typeof ExpensesRoute
  '/groups': typeof GroupsRoute
  '/import-csv': typeof ImportCsvRoute
  '/import-reports': typeof ImportReportsRoute
  '/settlements': typeof SettlementsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/balances': typeof BalancesRoute
  '/expenses': typeof ExpensesRoute
  '/groups': typeof GroupsRoute
  '/import-csv': typeof ImportCsvRoute
  '/import-reports': typeof ImportReportsRoute
  '/settlements': typeof SettlementsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/balances': typeof BalancesRoute
  '/expenses': typeof ExpensesRoute
  '/groups': typeof GroupsRoute
  '/import-csv': typeof ImportCsvRoute
  '/import-reports': typeof ImportReportsRoute
  '/settlements': typeof SettlementsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/balances'
    | '/expenses'
    | '/groups'
    | '/import-csv'
    | '/import-reports'
    | '/settlements'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/balances'
    | '/expenses'
    | '/groups'
    | '/import-csv'
    | '/import-reports'
    | '/settlements'
  id:
    | '__root__'
    | '/'
    | '/balances'
    | '/expenses'
    | '/groups'
    | '/import-csv'
    | '/import-reports'
    | '/settlements'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BalancesRoute: typeof BalancesRoute
  ExpensesRoute: typeof ExpensesRoute
  GroupsRoute: typeof GroupsRoute
  ImportCsvRoute: typeof ImportCsvRoute
  ImportReportsRoute: typeof ImportReportsRoute
  SettlementsRoute: typeof SettlementsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settlements': {
      id: '/settlements'
      path: '/settlements'
      fullPath: '/settlements'
      preLoaderRoute: typeof SettlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-reports': {
      id: '/import-reports'
      path: '/import-reports'
      fullPath: '/import-reports'
      preLoaderRoute: typeof ImportReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-csv': {
      id: '/import-csv'
      path: '/import-csv'
      fullPath: '/import-csv'
      preLoaderRoute: typeof ImportCsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balances': {
      id: '/balances'
      path: '/balances'
      fullPath: '/balances'
      preLoaderRoute: typeof BalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BalancesRoute: BalancesRoute,
  ExpensesRoute: ExpensesRoute,
  GroupsRoute: GroupsRoute,
  ImportCsvRoute: ImportCsvRoute,
  ImportReportsRoute: ImportReportsRoute,
  SettlementsRoute: SettlementsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
